# Generated by Django 4.0.4 on 2022-04-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_donor_address_remove_donor_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='tel',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
